### ISSUE TITLE
作者您好，想请问一下您在复现CasFusionNet的时候的具体参数比如初始下采样之后的点数以及上采样参数列表这些

### ISSUE THREAD

**Issue by shuaiqianende** [yyxssm/PointSSC#3]

**Comment by yyxssm** [comment]
Hi, this is our model configuration for CasFusionNet. We have configured the number of downsampled center points to 832 and set two upsample factors to [16, 16]:

```python
_target_: src.models.ssc_module.SSCLitModule

net:
  _target_: src.models.components.cas_fusion_net.CasFusionNet
  class_num: 18
  dim_feat: 1024
  num_p0: 832
  radius: 1.2
  up_factors: [ 16, 16]

loss:
  _target_: src.loss.ssc_loss.Loss
  seg_weight: null
  sqrt: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [ 0.9, 0.999 ]
  eps: 1e-08
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 2
  gamma: 0.99
  last_epoch: -1

dataset: ssc_pc

class_num: 18
```

**Comment by shuaiqianende** [comment]
还想了解一下具体的显存占用情况，目前只有4台3090方便做这个实验吗

**Comment by shuaiqianende** [comment]
> Hi, this is our model configuration for CasFusionNet. We have configured the number of downsampled center points to 832 and set two upsample factors to [16, 16]:
> 
> ```python
> _target_: src.models.ssc_module.SSCLitModule
> 
> net:
>   _target_: src.models.components.cas_fusion_net.CasFusionNet
>   class_num: 18
>   dim_feat: 1024
>   num_p0: 832
>   radius: 1.2
>   up_factors: [ 16, 16]
> 
> loss:
>   _target_: src.loss.ssc_loss.Loss
>   seg_weight: null
>   sqrt: True
> 
> optimizer:
>   _target_: torch.optim.Adam
>   _partial_: true
>   lr: 0.001
>   betas: [ 0.9, 0.999 ]
>   eps: 1e-08
>   weight_decay: 1e-4
> 
> scheduler:
>   _target_: torch.optim.lr_scheduler.StepLR
>   _partial_: true
>   step_size: 2
>   gamma: 0.99
>   last_epoch: -1
> 
> dataset: ssc_pc
> 
> class_num: 18
> ```

感谢感谢

**Comment by yyxssm** [comment]
I forgot the exact memory usage of CasFusionNet. For PointSSC model, the memory consumption during training is approximately 30GB.

If you encounter an "out of memory" issue, you can lower the upsampling factors to reduce the model's memory consumption. And you may downsample number of GT points to ensure consistency between training and inference.

**Comment by shuaiqianende** [comment]
还有一个问题，就是Pre-trained checkpoint那里训练好的模型下载不了，需要您核审通过一下

**Comment by yyxssm** [comment]
Thank you for the reminder. The link sharing permissions have been updated.
