### ISSUE TITLE
The dataset on Baidu Cloud is no longer downloadable. Has the link expired?

### ISSUE THREAD

**Issue by shuaiqianende** [yyxssm/PointSSC#4]

**Comment by shuaiqianende** [comment]
It seems that the **PointSSC** dataset you downloaded from Baidu Cloud does not contain the **infrastructure-side** folder.

**Comment by shuaiqianende** [comment]
It seems that the PointSSC dataset I downloaded from Baidu Cloud does not contain the infrastructure-side folder.

**Comment by yyxssm** [comment]
Thanks for reminder, we have update the [Baidu Cloud link](https://pan.baidu.com/s/1nNG7hOmat47Hdl4aBlHe3w?pwd=n6k6) (code: n6k6).

**Comment by yyxssm** [comment]
The data in PointSSC dataset from Baidu Cloud are infrastructure-side completion point clouds,  which is generated by our PointSSC pipeline. The `infrasturucture-side` and `vehicle-side` folder are raw data, you can download them from [here](https://thudair.baai.ac.cn/coop-forecast)

**Comment by shuaiqianende** [comment]
> The data in PointSSC dataset from Baidu Cloud are infrastructure-side completion point clouds, which is generated by our PointSSC pipeline. The `infrasturucture-side` and `vehicle-side` folder are raw data, you can download them from [here](https://thudair.baai.ac.cn/coop-forecast)

Thank you for the dataset, I will use it for my SSC experiment.

**Comment by shuaiqianende** [comment]
> The data in PointSSC dataset from Baidu Cloud are infrastructure-side completion point clouds, which is generated by our PointSSC pipeline. The `infrasturucture-side` and `vehicle-side` folder are raw data, you can download them from [here](https://thudair.baai.ac.cn/coop-forecast)

Could you provide a more accurate link to the input point cloud data? It seems I couldn't find one.

**Comment by shuaiqianende** [comment]
![image](https://github.com/user-attachments/assets/8b4ac240-840b-43de-8631-8559ba81b775)
I downloaded the file "V2X-Seq-SPD-infrastructure-side-velodyne" from the link you provided, and after extracting it, I got the PCD input point cloud files. However, the visualization results seem to have no direct correspondence with the ground truth (GT). Is there any processing required?

**Comment by shuaiqianende** [comment]
![image](https://github.com/user-attachments/assets/be7313fe-8b02-4af2-a166-0d9ef289c199)
It seems that the official website is currently down. Could you please directly send me the input point cloud link (via Baidu cloud storage or other methods)
